/* tslint:disable */
/* eslint-disable */
/**
 * Jstl.ink API
 * Jstl.ink gives users the ability to easily create simple pages containing for  them relevant links and their social media profiles
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePageRequest
 */
export interface CreatePageRequest {
    /**
     * ID of page
     * @type {string}
     * @memberof CreatePageRequest
     */
    id?: string;
}

/**
 * Check if a given object implements the CreatePageRequest interface.
 */
export function instanceOfCreatePageRequest(value: object): value is CreatePageRequest {
    return true;
}

export function CreatePageRequestFromJSON(json: any): CreatePageRequest {
    return CreatePageRequestFromJSONTyped(json, false);
}

export function CreatePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreatePageRequestToJSON(json: any): CreatePageRequest {
    return CreatePageRequestToJSONTyped(json, false);
}

export function CreatePageRequestToJSONTyped(value?: CreatePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

