/* tslint:disable */
/* eslint-disable */
/**
 * Jstl.ink API
 * Jstl.ink gives users the ability to easily create simple pages containing for  them relevant links and their social media profiles
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageIdRequestBody
 */
export interface PageIdRequestBody {
    /**
     * ID of page
     * @type {string}
     * @memberof PageIdRequestBody
     */
    id: string;
}

/**
 * Check if a given object implements the PageIdRequestBody interface.
 */
export function instanceOfPageIdRequestBody(value: object): value is PageIdRequestBody {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PageIdRequestBodyFromJSON(json: any): PageIdRequestBody {
    return PageIdRequestBodyFromJSONTyped(json, false);
}

export function PageIdRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageIdRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function PageIdRequestBodyToJSON(json: any): PageIdRequestBody {
    return PageIdRequestBodyToJSONTyped(json, false);
}

export function PageIdRequestBodyToJSONTyped(value?: PageIdRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

