/* tslint:disable */
/* eslint-disable */
/**
 * Jstl.ink API
 * Jstl.ink gives users the ability to easily create simple pages containing for  them relevant links and their social media profiles
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUp
 */
export interface SignUp {
    /**
     * ID of page
     * @type {string}
     * @memberof SignUp
     */
    id: string;
    /**
     * used as pathname in the url
     * @type {string}
     * @memberof SignUp
     */
    handle: string;
}

/**
 * Check if a given object implements the SignUp interface.
 */
export function instanceOfSignUp(value: object): value is SignUp {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('handle' in value) || value['handle'] === undefined) return false;
    return true;
}

export function SignUpFromJSON(json: any): SignUp {
    return SignUpFromJSONTyped(json, false);
}

export function SignUpFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'handle': json['handle'],
    };
}

export function SignUpToJSON(json: any): SignUp {
    return SignUpToJSONTyped(json, false);
}

export function SignUpToJSONTyped(value?: SignUp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'handle': value['handle'],
    };
}

