/* tslint:disable */
/* eslint-disable */
/**
 * Jstl.ink API
 * Jstl.ink gives users the ability to easily create simple pages containing for  them relevant links and their social media profiles
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Link,
  MutablePage,
  Page,
  SignUp,
} from '../models/index';
import {
    LinkFromJSON,
    LinkToJSON,
    MutablePageFromJSON,
    MutablePageToJSON,
    PageFromJSON,
    PageToJSON,
    SignUpFromJSON,
    SignUpToJSON,
} from '../models/index';

export interface CreatePageRequest {
    body: SignUp;
}

export interface CreatePageDetailsByPageIdRequest {
    pageId: string;
    body: MutablePage;
}

export interface DeletePageByPageIdRequest {
    pageId: string;
}

export interface GetCreatorPageByIdRequest {
    pageId: string;
}

export interface UpdatePageDetailsByPageIdRequest {
    pageId: string;
    body: MutablePage;
}

/**
 * 
 */
export class CreatorApi extends runtime.BaseAPI {

    /**
     * Create new user page
     */
    async createPageRaw(requestParameters: CreatePageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/creator`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignUpToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Create new user page
     */
    async createPage(requestParameters: CreatePageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.createPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Used to initialize user page with details - USE PATCH to actually update the details of user page
     * Create user page details
     */
    async createPageDetailsByPageIdRaw(requestParameters: CreatePageDetailsByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling createPageDetailsByPageId().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createPageDetailsByPageId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/creator/{pageId}`.replace(`{${"pageId"}}`, encodeURIComponent(String(requestParameters['pageId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MutablePageToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Used to initialize user page with details - USE PATCH to actually update the details of user page
     * Create user page details
     */
    async createPageDetailsByPageId(requestParameters: CreatePageDetailsByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.createPageDetailsByPageIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a user page
     */
    async deletePageByPageIdRaw(requestParameters: DeletePageByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling deletePageByPageId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/creator/{pageId}`.replace(`{${"pageId"}}`, encodeURIComponent(String(requestParameters['pageId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a user page
     */
    async deletePageByPageId(requestParameters: DeletePageByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePageByPageIdRaw(requestParameters, initOverrides);
    }

    /**
     * Get a user page
     */
    async getCreatorPageByIdRaw(requestParameters: GetCreatorPageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling getCreatorPageById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/creator/{pageId}`.replace(`{${"pageId"}}`, encodeURIComponent(String(requestParameters['pageId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Get a user page
     */
    async getCreatorPageById(requestParameters: GetCreatorPageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.getCreatorPageByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update details of user page
     */
    async updatePageDetailsByPageIdRaw(requestParameters: UpdatePageDetailsByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Link>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling updatePageDetailsByPageId().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updatePageDetailsByPageId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/creator/{pageId}`.replace(`{${"pageId"}}`, encodeURIComponent(String(requestParameters['pageId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MutablePageToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkFromJSON(jsonValue));
    }

    /**
     * Update details of user page
     */
    async updatePageDetailsByPageId(requestParameters: UpdatePageDetailsByPageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Link> {
        const response = await this.updatePageDetailsByPageIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
