/* tslint:disable */
/* eslint-disable */
/**
 * Jstl.ink API
 * Jstl.ink gives users the ability to easily create simple pages containing for  them relevant links and their social media profiles
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Page,
} from '../models/index';
import {
    PageFromJSON,
    PageToJSON,
} from '../models/index';

export interface GetPageByHandleRequest {
    handle: string;
}

/**
 * 
 */
export class PageApi extends runtime.BaseAPI {

    /**
     * Returns a single page
     * Get page by handle
     */
    async getPageByHandleRaw(requestParameters: GetPageByHandleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['handle'] == null) {
            throw new runtime.RequiredError(
                'handle',
                'Required parameter "handle" was null or undefined when calling getPageByHandle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{handle}`.replace(`{${"handle"}}`, encodeURIComponent(String(requestParameters['handle']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Returns a single page
     * Get page by handle
     */
    async getPageByHandle(requestParameters: GetPageByHandleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.getPageByHandleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
